# Generated by Django 3.1.4 on 2021-01-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=15)),
                ('would_take_again', models.CharField(max_length=3)),
                ('difficulty', models.FloatField()),
                ('quality', models.FloatField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
